# This workflow will build a Golang project and push it to Docker
name: Go and Docker Image(GHCR)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.4'

    - name: Build
      run: go build -v ./...

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: mdNoman21
        password: ${{ secrets.GH_PAT }}

    - name: Build Docker image
      run: docker build -t ghcr.io/mdnoman21/cdm:ec3ae3b .

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/mdnoman21/cdm:ec3ae3b
